### ISSUE TITLE
Specify custom queue for producer to push messages

### ISSUE THREAD

**Issue by umahanov** [php-enqueue/enqueue-dev#1001]
Hi.

I'm using this package within Symfony 4.4.
I have configured processor with custom queue, because I don't want to read and write messages to **enqueue.app.default** queue.

So my processor service configuration is:

 ```
cache_processor:
    class: My\CacheProcessor
    arguments:
      - '@My\CacheUpdater'
    tags:
      - { name: enqueue.processor, processor: 'my_cache', queue: 'my_cache', topic: !php/const My\CachePublisher::SUBSCRIBED_TOPIC }

```

As you can see here, the queue is **my_cache** and after calling 

```
php bin/console enqueue:setup-broker
```
I can see it in my rabbitMQ web interface.

My **CachePublisher** sends message through producer:

`$this->producer->sendEvent($this->getSubscribedTopic(), $this->message)`

where `getSubscribedTopic()` returns **topic** parameter value from processor's tag specified earlier.

The problem is that it sends all messages to **enqueue.app.default** queue, while I expect it to push them to the **my_cache** queue.

Maybe I don't understand something. Any help appreciated.
