### ISSUE TITLE
RdKafka transport does not support merging for `global` configuration

### ISSUE THREAD

**Issue by Wirone** [php-enqueue/enqueue-dev#1002]
Considering:

```
# config/packages/enqueue.yaml
enqueue:
    default:
        transport:
            dsn: "rdkafka://"
            global:
                bootstrap.servers: '%env(KAFKA_BOOTSTRAP_SERVERS)%'
                security.protocol: ssl
                group.id: '%env(KAFKA_GROUP_ID)%'
                ssl.ca.location: '%env(KAFKA_ROOT_CA)%'
                ssl.certificate.location: '%env(KAFKA_CERT)%'
                ssl.key.location: '%env(KAFKA_KEY)%'
                enable.ssl.certificate.verification: 'false'
                ssl.endpoint.identification.algorithm: 'none'
                enable.auto.commit: 'true'
            topic:
                auto.offset.reset: latest
        client: ~
```

and

```
# config/packages/dev/enqueue.yaml
enqueue:
    default:
        transport:
            global:
                debug: all
```

I would like `debug: all` to be merged to `global` configuration from main configuration.

Unfortunately it does not work this way (`enqueue-bundle` 0.9.13), the final config for `global` is taken from last occurence.

It works when I add:

```
->arrayNode('global')
    ->ignoreExtraKeys(false)
->end()
```

to the `Enqueue\Symfony\DependencyInjection\TransportFactory::getConfiguration()`. Symfony's DI container has to know that there is `global` node with array type, which can take any options.

:information_source: Would be great if it could be fixed in `0.9` branch because we're using `sroze/messenger-enqueue-transport` which currently does not allow using Enqueue `0.10`.
