### ISSUE TITLE
Symfony Bundle: be explicit about service tags with "enqueue.consumption.extension"

### ISSUE THREAD

**Issue by wirwolf** [php-enqueue/enqueue-dev#1010]
If I use multiple connections when I register extension in service, this extension applies only one instance. 
enqueue version: 0.10
packages/enqueue.yaml
```
enqueue:
    default:
        transport: 'amqp+lib://%enqueue.amqp.user%:%enqueue.amqp.pass%@%enqueue.amqp.host%:%enqueue.amqp.port%/%enqueue.amqp.vhost%?heartbeat_on_tick=1'
        client:
            prefix: '%enqueue.client.prefix%'
            app_name: '%enqueue.client.app%'
        job: true
        async_commands: true

    task:
        transport: 'amqp+lib://%enqueue.amqp.user%:%enqueue.amqp.pass%@%enqueue.amqp.host%:%enqueue.amqp.port%/%enqueue.amqp.vhost%?heartbeat_on_tick=1'
        client:
            prefix: '%enqueue.client.prefix%'
            app_name: '%enqueue.task.client.app%'
        async_commands: true

    taskevent:
        transport: 'amqp+lib://%enqueue.amqp.user%:%enqueue.amqp.pass%@%enqueue.amqp.host%:%enqueue.amqp.port%/%enqueue.amqp.vhost%?heartbeat_on_tick=1'
        client:
            prefix: '%enqueue.client.prefix%'
            app_name: '%enqueue.taskevent.client.app%'
        async_commands: true
```

services/services.yaml

```
    AdgoalCommon\FaultTolerance\RabbitEnqueue\QueueFaultTolerantExtension:
        autowire: true
        tags:
            - { name: 'enqueue.consumption.extension', priority: 10 }
```

**Comment by makasim** [comment]
https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/enqueue/Symfony/Client/DependencyInjection/BuildConsumptionExtensionsPass.php#L39

**Comment by Steveb-p** [comment]
As makasim pointed out, your tag has to specify which client it should apply to - or use `all` to denote that it should apply to every client.

```yaml
    AdgoalCommon\FaultTolerance\RabbitEnqueue\QueueFaultTolerantExtension:
        autowire: true
        tags:
            - { name: 'enqueue.consumption.extension', priority: 10, client: 'all' }
```
...and you should be good to go.
