### ISSUE TITLE
Integration of enqueue with easyadmin 

### ISSUE THREAD

**Issue by jmeyo** [php-enqueue/enqueue-dev#1024]
Hi,
I am trying to integrate enqueue library with easyadmin, in order to be able to see the messages through easyadmin. We are using enqueue with dbal transport, and we have several clients controlled with supervisor.
By creating a sortof virtual entity for the enqueue message, we are able to list the messages in easyadmin and we can work on additional features through the easyadmin library like counting, browsing, deleting messages.

But then doctrine migration are not possible as the supervisor call the setup broker continuously and create enqueue table, which lead to doctrine migration crashing as the entity enqueue already exist.

We tried to avoid managing the enqueue entity with the shema_filter option of doctrine, but somehow it doesnt work. 

Is it the proper way ? Does anyone achieved to integrate enqueue with easyadmin and doctrine migrations ?

The doctrine conf
```
doctrine:
    dbal:
        # configure these for your database server
        default_connection: default
        connections:
            default:
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci

                url: '%env(resolve:DATABASE_URL)%'
                schema_filter: ~^(?!enqueue)~
```

here is the easyadmin conf
```
    Enqueue:
      label: 'Message Queue'
      class: App\Entity\Enqueue
      show:
        fields:
          - { property: 'id', label: 'Id' }
          - { property: 'publishedAt', template: 'admin/common/field_microtimestamp.html.twig' }
          - { property: 'queue', label: 'queue' }
          - { property: 'headers', label: 'Headers' }
          - { property: 'body', label: 'Body' }
          - { property: 'properties', label: 'Properties' }
          - { property: 'priority', label: 'Priority' }
          - { property: 'redelivered' }
      list:
        title: 'List of message in the queue'
        fields:
          - { property: 'id', label: 'Id' }
          - { property: 'publishedAt', template: 'admin/common/field_microtimestamp.html.twig' }
          - { property: 'queue', label: 'queue' }
          - { property: 'redelivered', type: 'boolean' }
          - { property: 'body', label: 'Body' }
          - { property: 'priority', label: 'Priority' }
        actions: ['show', '-delete']
        sort: ['publishedAt', 'DESC']
        filters: ['queue', 'redelivered', 'priority']
```
and the entity
```
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity()
 */
class Enqueue
{
    /**
     * @ORM\Id()
     * @ORM\Column(type="string", length=64)
     */
    private $id;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $body;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $headers;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $priority;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $queue;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $redelivered;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $delayedUntil;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $properties;

    /**
     * @ORM\Column(type="bigint", nullable=true)
     */
    private $publishedAt;

    public function getId(): ?string
    {
        return $this->id;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(?string $body): self
    {
        $this->body = $body;

        return $this;
    }

    public function getHeaders(): ?string
    {
        return $this->headers;
    }

    public function setHeaders(string $headers): self
    {
        $this->headers = $headers;

        return $this;
    }

    public function getPriority(): ?int
    {
        return $this->priority;
    }

    public function setPriority(?int $priority): self
    {
        $this->priority = $priority;

        return $this;
    }

    public function getQueue(): ?string
    {
        return $this->queue;
    }

    public function setQueue(?string $queue): self
    {
        $this->queue = $queue;

        return $this;
    }

    public function getRedelivered(): ?int
    {
        return $this->redelivered;
    }

    public function setRedelivered(?int $redelivered): self
    {
        $this->redelivered = $redelivered;

        return $this;
    }

    public function getDelayedUntil(): ?int
    {
        return $this->delayedUntil;
    }

    public function setDelayedUntil(?int $delayedUntil): self
    {
        $this->delayedUntil = $delayedUntil;

        return $this;
    }

    public function getProperties(): ?string
    {
        return $this->properties;
    }

    public function setProperties(?string $properties): self
    {
        $this->properties = $properties;

        return $this;
    }

    public function getPublishedAt(): ?int
    {
        return $this->publishedAt;
    }

    public function setPublishedAt(?int $publishedAt): self
    {
        $this->publishedAt = $publishedAt;

        return $this;
    }
}```
