### ISSUE TITLE
Kafka sasl_ssl settings for confluent.io 

### ISSUE THREAD

**Issue by iBasit** [php-enqueue/enqueue-dev#1029]
In symfony 5 getting `No such configuration property: "ssl.endpoint.identification.algorithm"`

`ssl.endpoint.identification.algorithm` 
 is part of https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md configuration settings, which is mentioned in https://php-enqueue.github.io/transport/kafka/#installation - so I'm kind of confuse what I'm doing wrong. can you help here, please?

enqueue.yml
```
enqueue:
    default:
        async_events:
            enabled: true
        transport:
            dsn: "rdkafka://"
            global:
                group.id: 'myapp'
                metadata.broker.list: "%env(KAFKA_BROKER_LIST)%"
                ssl.endpoint.identification.algorithm: https
                security.protocol: sasl_ssl
#                ssl.ca.location: '%kernel.project_dir%/config/kafka/ca.pem'
                sasl.username: 'UEJD63D62BTE3F3N'
                sasl.password: 'adfasdfasdfasdfaasdf+nTZM33z9jhk7lQUmv8RatZwwaE2HLs'
                sasl.mechanisms: "PLAIN"
                max.poll.interval.ms: '25000'
                enable.auto.commit: 'false'
                enable.auto.offset.store: 'false'
            topic:
                auto.offset.reset: beginning
            commit_async: true
        client: ~
```

```
"enqueue/async-event-dispatcher": "^0.10.1",
        "enqueue/enqueue": "^0.10.1",
        "enqueue/enqueue-bundle": "^0.10.1",
        "enqueue/rdkafka": "^0.10.1",
        "league/commonmark": "^1.3",
        "lexik/jwt-authentication-bundle": "^2.6",
        "sroze/messenger-enqueue-transport": "^0.5.0",
```

```
rdkafka extension 4.0.2
```
