### ISSUE TITLE
[redis] Impossible to use Redis instance created by the SncRedis bundle

### ISSUE THREAD

**Issue by pmishev** [php-enqueue/enqueue-dev#1061]
Related to https://github.com/php-enqueue/enqueue-dev/issues/341

Since 0.9 it is impossible to pass a redis object to RedisConnectionFactory with Symfony. If you try to do it like this:
```
    redis:
        transport:
            dsn: '@enqueue_redis_client'
            connection_factory_class: 'Enqueue\Redis\RedisConnectionFactory'
```
you get 
```
The DSN is invalid. It does not have scheme separator ":".
```
