### ISSUE TITLE
A given scheme "enqueue" is not supported. Maybe it is a custom connection, make sure you registered it with "Enqueue\Resources::addConnection"

### ISSUE THREAD

**Issue by kdefives** [php-enqueue/enqueue-dev#1086]
Hello,

I try to use Google Pub/Sub with enqueue inside a Symfony 5.1 but I faced this error message :
```
A given scheme "enqueue" is not supported. Maybe it is a custom connection, make sure you registered it with "Enqueue\Resources::addConnection".
```

Do you know if i missed something and please can you help me?
My enqueue.yaml:
```yaml
enqueue:
    default:
        transport:
            dsn: '%env(resolve:ENQUEUE_DSN)%'
            gps:
                projectId: '%env(resolve:GOOGLE_PROJECT_ID)%'
                keyFilePath: '%env(resolve:GOOGLE_APPLICATION_CREDENTIALS)%'
        client: ~
```

My messenger.yaml:
```yaml
framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'
            default: 'amqp://guest:guest@localhost:5672/%2f/messages'
            enqueue: 'enqueue://gps'

        default_bus: messenger.bus.commands
        buses:
            messenger.bus.commands: ~
            messenger.bus.events: ~

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
            'App\Message\JobDataFromOneCatalog': enqueue

```

My .env file:
```yaml
###> symfony/messenger ###
# Choose one of the transports below
# MESSENGER_TRANSPORT_DSN=amqp://guest:guest@localhost:5672/%2f/messages
# MESSENGER_TRANSPORT_DSN=doctrine://default
# MESSENGER_TRANSPORT_DSN=redis://localhost:6379/messages
###< symfony/messenger ###

###> enqueue/enqueue-bundle ###
#ENQUEUE_DSN=null://
ENQUEUE_DSN=enqueue://gps
###< enqueue/enqueue-bundle ###

###> enqueue/gps ###
#PUBSUB_EMULATOR_HOST=http://localhost:8900
###< enqueue/gps ###

GOOGLE_PROJECT_ID=my-project-id
GOOGLE_APPLICATION_CREDENTIALS=C:\Development\my-project\app\my-service-account.json
```

Thx in advance for you help!

**Comment by kdefives** [comment]
Ok, in my enqueue.yaml i replaced
dsn: '%env(resolve:ENQUEUE_DSN)%'
by
dsn: 'gps:'

But know i have this error : Can't find Enqueue's transport named "gps": Service "enqueue.transport.gps.context" is not found.

Do I have to declare a Service? I thought it was done automatically with config, no?

**Comment by makasim** [comment]
Does GPS work with enqueue publisher\consumer ?

**Comment by kdefives** [comment]
> Does GPS work with enqueue publisher\consumer ?

I am using https://php-enqueue.github.io/transport/gps/

**Comment by makasim** [comment]
I mean, without symfony messenger, does it work ?

**Comment by kdefives** [comment]
don't know. But i continue to try this morning and everything is ok with that conf : 

```yaml
# messenger.yaml
framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'
            # default: 'amqp://guest:guest@localhost:5672/%2f/messages'
            enqueue: 'enqueue://gps?queue[name]=%env(resolve:PUBSUB_SUBSCRIPTION_NAME)%&topic[name]=%env(resolve:PUBSUB_TOPIC_NAME)%&%env(resolve:PUBSUB_PARAMETERS)%'

        default_bus: messenger.bus.commands
        buses:
            messenger.bus.commands: ~
            messenger.bus.events: ~

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
            'App\Message\JobDataFromOneCatalog': enqueue
```

```yaml
# enqueue.yaml
enqueue:
    gps:
        transport:
            dsn: 'gps:gps?projectId=%env(resolve:GOOGLE_PROJECT_ID)%&keyFilePath=%env(resolve:GOOGLE_APPLICATION_CREDENTIALS)%&queue[name]=%env(resolve:PUBSUB_SUBSCRIPTION_NAME)%&topic[name]=%env(resolve:PUBSUB_TOPIC_NAME)%'
            #connection_factory_class: Enqueue\Gps\GpsConnectionFactory
        client: ~
```

We can conclude it is working with Symfony Messenger :)
