### ISSUE TITLE
Enqueue symfony-bundle PDO MySQL SSL certifcate verification

### ISSUE THREAD

**Issue by FrankHouwelingCastor** [php-enqueue/enqueue-dev#1125]
Hello!

I'm currently trying to enable SSL certificate verification with enqueue and the symfony bundle, and it's not working correctly. This is my configuration:

```
enqueue:
    default:
        transport: '%env(resolve:DATABASE_URL)%'
        client:
            traceable_producer:   true
            prefix:               enqueue
            separator:            .
            app_name:             myapp
            router_topic:         default
            router_queue:         default
            router_processor:     null
            redelivered_delay_time: 0
            default_queue:        default
            driver_options:
              !php/const:PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT: true
              !php/const:PDO::MYSQL_ATTR_SSL_CA: '/my/path/to/ca-certificates.crt'
        async_events:
            enabled: true
```

These driver_options are the same as my options in doctrine dbal config, where they do work.

Thank you for your help.

**Comment by FrankHouwelingCastor** [comment]
We ended up with overwriting the enqueue.transport.default.connection_factory like this:

```
    enqueue.transport.default.connection_factory:
        class: Enqueue\Dbal\ManagerRegistryConnectionFactory
        arguments:
            - "@doctrine"
            - connection_name: "default" 
```

This way, we could reuse the connection from doctrine, where we could easily set the required PDO params:

```
doctrine:
    dbal:
        options:
            !php/const:PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT: true
            !php/const:PDO::MYSQL_ATTR_SSL_CA: '/my/path/to/ca-certificates.crt'

```
