### ISSUE TITLE
AMQPException Library error: a SSL error occurred

### ISSUE THREAD

**Issue by Webonaute** [php-enqueue/enqueue-dev#1162]
I have issue with SSL connection. 

We are using AWS RabbitMQ service.
Broker engine version : 3.8.6

```
AMQPException Library error: a SSL error occurred
"file" => "/project/vendor/enqueue/amqp-ext/AmqpConsumer.php","line" => 121,"trace" => """ #0 /project/vendor/enqueue/amqp-ext/AmqpConsumer.php(121): AMQPQueue->ack()\n #1 /project/vendor/enqueue/enqueue/Consumption/QueueConsumer.php(210)
```

Its happen from time to time, and only when it come to acknowledge a message.

Symfony configuration:
```
enqueue:
    default:
        job:
            enabled: true
        transport:
            dsn: 'amqps+tls+rabbitmq:'
            host: '%env(MQ_HOST)%'
            vhost: '%env(MQ_VHOST)%'
            port: '%env(MQ_PORT)%'
            user: '%env(MQ_USER)%'
            pass: '%env(MQ_PASSWORD)%'
            connection_name: '%env(SERVICE_NAME)%-%api_version%'
            heartbeat: 60  # <--- note that I have try without heartbeat as well.
            ssl_on: true
            ssl_cacert: '%default_cert_file%'
        client:
            router_topic: 'worker'
            router_queue: operational
            prefix: '%kernel.environment%'
            default_queue: operational
```

It also happen only on our worker servers who consume the message. No issue with producer.

any idea how to resolve this?
