### ISSUE TITLE
Symfony message sent but not inside rabbitmq

### ISSUE THREAD

**Issue by syntaxgirl** [php-enqueue/enqueue-dev#1186]
I have setup enqueue following documentation, example

```
enqueue.yaml
enqueue:
    default:
        transport: "amqp://guest:guest@localhost:5672/%2f"
        client: ~
```
and then tested it from a controller with
```
        $properties = [];
        $headers = [];
        $message = new Message('Message body', $properties, $headers);
        $this->producer->sendEvent('messages', $message);
```

![image](https://user-images.githubusercontent.com/57375816/126454364-d52c571a-b84e-4e27-9502-6ce80cd03059.png)

As you can see, it does say it is send out, but nothing is inside rabbitmq.
If I try to send out command I get `There is no route for command "<commandname>"`
