### ISSUE TITLE
DBAL Transport: polling_interval not taken into account

### ISSUE THREAD

**Issue by maps82** [php-enqueue/enqueue-dev#121]
Hi!

I use the dbal transport for local development with symfony. Changing the polling_interval has no effect. It seems as the polling interval is always one second.

**Comment by makasim** [comment]
@maps82 How do you configure the transport?

**Comment by maps82** [comment]
The configuration is:
```
enqueue:
    transport:
        default: 'dbal'
        dbal:
            dbal_connection_name: 'default'
            table_name: 'enqueue'
            # How often query for new messages.
            polling_interval: 20000
            lazy: true
```
