### ISSUE TITLE
Using messages with different routing key inside single queue

### ISSUE THREAD

**Issue by syntaxgirl** [php-enqueue/enqueue-dev#1219]
Hi. I am using external system which uses 1 queue, with messages which are using different routing keys. Now I want to bind each message with corresponding handler, but to do it, I need to bind it based on a routing key. Now I am using Shopware 6, which use enqueue-dev library. I am using basic setup of a transport

```
# config/packages/framework.yaml
framework:
    messenger:
        transports:
            default:
                dsn: "enqueue://rabbitmq?queue[name]=shopware-queue"
```
But how to add routing/binding key?  I tried with
```
&queue[bindingKey]=foo.#
```
But that didn't worked. I tried also with 
```
&metadata[routingKey]=foo.#
```
But this didn't worked also. Any tip?
