### ISSUE TITLE
Filesystem transport: The "failed" receiver does not support listing or showing specific messages

### ISSUE THREAD

**Issue by Hubbitus** [php-enqueue/enqueue-dev#1226]
Hello.

I've setup failed transport as local filesystem write:
config/packages/messenger.yaml:
```yaml
framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            async_kafka:
               ...
            failed:
                dsn: 'enqueue://enqueue_file?topic[name]=fails'

        routing:
            # Route your messages to the transports
            'App\DAO\DemoNotification': [ async_kafka ]
```

config/packages/enqueue.yaml:
```yaml
enqueue:
    enqueue_file:
        transport:
            dsn: 'file://'
            path: '%kernel.project_dir%/var/queue/kafka.mirror'
```

Together with configuring custom middleware by https://github.com/symfony/symfony/issues/35521 I be able to send messages into failed ques when Kafka is not available.

Meantime I can't read that:
```shell
bin/console messenger:failed:show
[critical] Error thrown while running command "messenger:failed:show". Message: "The "failed" receiver does not support listing or showing specific messages."
```
