### ISSUE TITLE
AmqpConsumer::receiveBasicGet, only one message per timeout consumed

### ISSUE THREAD

**Issue by dkarlovi** [php-enqueue/enqueue-dev#159]
I've upgraded to 0.6 couple of days ago and I'm seeing a regression in `AmqpConsumer::receiveBasicGet`
basically, it will only receive one message per timeout, for some reason.

Say I have say 10 messages in a queue, it will only receive the first one and stall, reach timeout, retry and then receive another. I've added some debug statements in the `while()` loop and after `usleep()`, it will go like:

    message
    ............ # outputing a single dot every while iteration
    <timeout>
    message
    ............ # outputing a single dot every while iteration
    <timeout>

No matter how many messages there are ready to process in the queue. If I set `$timeout = 1` to the top of the method, everything works as expected so it shouldn't be related to my processors being slow or hanging.

I've cleared my RabbitMQ Docker volume to avoid any possible misconfiguration between 0.5 and 0.6, it did not help. Using ext/amqp 1.9.0 (which I also used on 0.5).

**Comment by makasim** [comment]
@dkarlovi Could you please provide more information about your setup and if possible code snippets. The libs versions, a framework if used, configs, do you use the enqueue client or amqp transport directly. do you ack messages?

**Comment by dkarlovi** [comment]
Sure, using:
- PHP 7.1.5 from Docker Alpine 3.6, ext/amqp 1.9.0
- RabbitMQ 3.6.10
- Symfony 3.3.6 + Enqueue bundle (config below)
- running `bin/console enqueue:consume --setup-broker -vvv`, I can see the delay and described debug output there

Will try to downgrade to 0.5 to figure out where exactly the regression comes from. Might also disable my processors and just leave the built-in debug output.

```yaml
enqueue:
    async_events:
        enabled: true
        # spool_producer: true
    transport:
        default: 'rabbitmq_amqp'
        rabbitmq_amqp:
            host: '%broker_host%'
            port: '%broker_port%'
            user: '%broker_user%'
            pass: '%broker_password%'
            vhost: '%broker_name%'
            persisted: true
            delay_plugin_installed: true
    client:
        traceable_producer: '%kernel.debug%'
    job: true
    extensions:
        doctrine_ping_connection_extension: true
        doctrine_clear_identity_map_extension: true
        signal_extension: true
```
