### ISSUE TITLE
Error on PurgeFosElasticPopulateQueueListener::__construct()

### ISSUE THREAD

**Issue by daviddlv** [php-enqueue/enqueue-dev#174]
Hi,

I try to populate ElasticSearch by executing command `fos:elastica:populate` but i've got this error :
```
[Symfony\Component\Debug\Exception\FatalThrowableError]                                                                                                                                                                                    
  Type error: Argument 1 passed to Enqueue\ElasticaBundle\Listener\PurgeFosElasticPopulateQueueListener::__construct() must implement interface Interop\Queue\PsrContext, instance of Enqueue\Client\Producer given, called in /app/var/cac  
  he/dev/appDevDebugProjectContainer.php on line 2607
```

My config is :
```
enqueue:
    transport:
        default: 'file://%kernel.root_dir%/../var/messages'
    client: ~
```

Is it a bug ?
