### ISSUE TITLE
[Elastica] persistence.driver = orm is optional

### ISSUE THREAD

**Issue by dkarlovi** [php-enqueue/enqueue-dev#245]
With FOS Elastica 4.0, setting 

```yaml
fos_elastica:
    indexes:
        index:
            types:
                type:
                    persistence:
                        driver: orm
```

is implied, but [Enqueue Elastica expect it to be set](https://github.com/php-enqueue/enqueue-elastica-bundle/blob/master/DependencyInjection/Compiler/AsyncProviderCompilerPass.php#L19), throwing a notice if not.
