### ISSUE TITLE
[enqueue-bundle] Confused about creating enqueue_job and enqueue_job_unique tables (question)

### ISSUE THREAD

**Issue by msheakoski** [php-enqueue/enqueue-dev#277]
I have read through all of the enqueue documentation and I am not sure if I am going about this the right way. I set up the Symfony bundle with job:true and DBAL transport. I can consume messages just fine, but when I try to use the JobRunner in my consumer, I get an error about the "enqueue_job_unique" relation not existing. The "enqueue" database table is created, but the tables for the Job and JobUnique entities are not. Shouldn't they be automatically created just like the "enqueue" table?

If the tables are not automatically created, is the correct process to run `console doctrine:migrations:diff && console doctrine:migrations:migrate`? If so, I can submit a patch to the docs because this is very confusing to enqueue newcomers.

**Comment by makasim** [comment]
The code was inherited from ORO. It has stayed untouched since then. 

https://github.com/oroinc/OroMessageQueueBundle/blob/master/Migrations/Schema/OroMessageQueueBundleInstaller.php#L51

**Comment by makasim** [comment]
I am thinking of a similar solution we used in [dbal transport](https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/dbal/DbalContext.php#L165). One based on doctrine dbal.

**Comment by msheakoski** [comment]
I like this idea because it also allows for both easier configuration and also easier updates of Enqueue by separating the table from your app.

**Comment by makasim** [comment]
It turned out to be super easy. You  dont have to deal with schemas at all, there are entities, just register them:

```
doctrine:
    # ...
    orm:
        # ...
        mappings:
            EnqueueJobQueue:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/vendor/enqueue/job-queue/Doctrine/mapping'
                prefix: 'Enqueue\JobQueue\Doctrine\Entity'
```
