### ISSUE TITLE
[bundle] The bundle  does not work correctly with env parameters set as tag attr.

### ISSUE THREAD

**Issue by makasim** [php-enqueue/enqueue-dev#28]
This does not work

```yaml
# app/config/config.yml

parameters:
    enqueue_router_topic: '%env(ENQUEUE_ROUTER_TOPIC)%'
    enqueue_router_queue: '%env(ENQUEUE_ROUTER_QUEUE)%'

enqueue:
    client:
        router_topic: '%enqueue_router_topic%'
        router_queue: '%enqueue_router_queue%'
```

If you run `./bin/console enqueue:queue` it does not show any queues accept router one.
