### ISSUE TITLE
[SQS] Enable long polling to reduce the number of empty receives

### ISSUE THREAD

**Issue by jverdeyen** [php-enqueue/enqueue-dev#307]
Hello,

I'm using SQS as client in a Symfony 3.4 project.

I run a cron every five minutes to restart the consumer:

```
/bin/sh -c /usr/bin/php /var/www/project/current/bin/console enqueue:consume --setup-broker --time-limit="now + 4min" --env=staging
```

All goes fine, things are consumed properly.
But I received an email from amazone that in less than 7 days I used 1.000.000 requested (no more free tier).

This is whats happening: [request graph](https://www.dropbox.com/s/isqlum8fpzpr9g6/Screenshot%202017-12-31%2022.09.04.jpg?dl=0)

I've been reading that I can avoid this by using long polling?
https://aws.amazon.com/sqs/faqs/
https://docs.aws.amazon.com/aws-sdk-php/v3/guide/examples/sqs-examples-enable-long-polling.html

Any idea how I can do this in enqueue? Create a long poll queue and consome with long polling?
What is the best practice for this ?

This is my `config.yml`

```
enqueue:
    transport:
        default: 'sqs'
        sqs:
            key:                  "%aws_s3_key%"
            secret:               "%aws_s3_secret%"
            token:                ~
            region:               eu-west-1
            retries:              3
            version:              '2012-11-05'
            lazy:                 true
    client:
        app_name: '%app_name%_%kernel.environment%'
        default_processor_queue: 'default'
        traceable_producer: true
    async_events: false
    job: false
```

Thanks!

**Comment by makasim** [comment]
It is already [there](https://github.com/php-enqueue/enqueue-dev/blob/d5609d8e1e440af543662bbe25206dc069b93ec0/pkg/sqs/SqsConsumer.php#L178). 

We don't set a `ReceiveMessageWaitTimeSeconds` on queue creation. But a quick test shows that it waits for 20 seconds. 

Try setting `--receive-time=20000` (20s) option on the consume command.

**Comment by makasim** [comment]
Feel free to reopen if there is something left

**Comment by CHenzel** [comment]
Hi,

I have the same problem and the setting "--receive-time=20000" not working with consume command

`bin/console enqueue:consume --env=dev --receive-time=20000 =>  The "--receive-time" option does not exist.`

This setting change for --receive-timeout ? I

`bin/console enqueue:consume --env=dev --receive-timeout=20000`

I try but is not better, when i start consume command the "numberOfEmptyReceives" on aws sqs explode (> 5000) without send and consume messages and the queue parameter **Receive Message Wait Time** is set to 0.

How we can set ReceiveMessageWaitTimeSeconds to 20 seconds ?

This is my `config.yml`

```
enqueue:
    default:
        transport: "sqs:?key=%amazon_web_services.key%&secret=%amazon_web_services.secret%&region=ca-central-1&lazy=true&retries=1"
        consumption:
            receive_timeout: 20000
        client:
            prefix: %kernel.environment%
            app_name: myapp
            traceable_producer: true

```
code for sent message
```
  /** @var ProducerInterface $producer **/
$producer = $this->container->get(\Enqueue\Client\ProducerInterface::class);
$producer->sendEvent('synchro_product_delete', serialize(['product_id' => $oldProductId]));
```
Service:

```
    product_delete_event_subscriber:
        class:ApiPublicBundle\EventListener\ProductDeleteEventSubscriber
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: 'enqueue.topic_subscriber', topicName: 'synchro_product_delete' }
```
ProductDeleteEventSubscriber:

```
    public static function getSubscribedTopics()
    {
        return [
            [
                'topic' => 'synchro_product_delete',
                'queue' => 'enqueue_synchro_product_delete',
            ]
        ];
    }

    public function process(Message $message, Context $context)
    {
        $body = unserialize($message->getBody());
         //code
        return self::ACK;
    }
```


Thanks for your help
