### ISSUE TITLE
SQS via DNS region missing

### ISSUE THREAD

**Issue by iaejean** [php-enqueue/enqueue-dev#321]
I'm using SF4 with Flex and enqueue bundle, and I getting the follow messages:

```
Missing required client configuration options: 

region: (string)

  A "region" configuration value is required for the "sqs" service
  (e.g., "us-west-2"). A list of available public regions and endpoints can be
  found at http://docs.aws.amazon.com/general/latest/gr/rande.html.
```

I have the follow settings: 
env file:

```
###> enqueue/enqueue-bundle ###
ENQUEUE_DSN=sqs://key={KEY}&secret={SECRET}&region=us-east-1
###< enqueue/enqueue-bundle ###
```

enqueue yaml file:
```yaml
enqueue:
    transport:
        default: '%env(ENQUEUE_DSN)%'
    client: ~
```
