### ISSUE TITLE
Does redis factory supports sentinel or cluster?

### ISSUE THREAD

**Issue by charleslxh** [php-enqueue/enqueue-dev#341]
I use [SncRedisBundle](https://github.com/snc/SncRedisBundle) in `symfony`, how can I config a `snc_redis.client` as  the enqueue's redis connection driver.

```
enqueue:
    transport:
         
```

**Comment by charleslxh** [comment]
I saw the `enqueue/redis`,  and it seems not supported `sentinel` or `cluster`.

**Comment by makasim** [comment]
Passing redis object to connection factory is not possible at the moment. Would you like to send us a PR?

**Comment by charleslxh** [comment]
This feature will affect many components, such as `DefaultTransportFactory` in enqueue, `Configuration` in enqueue-bundle, `RedisTransportFactory` and `RedisConnectionFactory` in redis.

**Comment by charleslxh** [comment]
Please take a revier! @makasim

**Comment by makasim** [comment]
This should solve the issue https://github.com/php-enqueue/enqueue-dev/issues/367#issuecomment-365867762

**Comment by makasim** [comment]
```yaml

services:
     enqueue_redis_client: 
         class: Enqueue\Redis\PRedis
         arguments: ['@snc_redis.client']

enqueue:
  transport:
    redis:
      vendor: custom
      redis: enqueue_redis_client
```

**Comment by pmishev** [comment]
Is this still possible to do with the new config structure in 0.10?

**Comment by pmishev** [comment]
It looks like this has been broken here: https://github.com/php-enqueue/redis/commit/d6d21480d23a1351220614165f4b2f7c7fd6eb3c#diff-8e8970cea30c8c83bfe7de0e4d4470e4L18 and is now no longer possible to set a Predis\ClientInterface to PRedis.

I can see that RedisConnectionFactory now can accept Enqueue\Redis instance, but it's not possible to pass that either:

I tried doing:
```
    redis:
        transport:
            dsn: '@enqueue_redis_client'
            connection_factory_class: 'Enqueue\Redis\RedisConnectionFactory'
```
but I get:
`The DSN is invalid. It does not have scheme separator ":".`
