### ISSUE TITLE
[SQS] Unable to connect to FIFO queue

### ISSUE THREAD

**Issue by frak** [php-enqueue/enqueue-dev#342]
I am setting up the Symfony bundle of your library and have hit a bit of a problem trying to connect to a pre-existing FIFO queue.

I have enabled the bundle and I have configured it as follows:

```
enqueue:
    transport:
        default: sqs
        sqs:
            key: '%aws_key%'
            secret: '%aws_secret%'
            region: 'eu-west-1'
            retries: 3
            version: '2012-11-05'
            lazy: true
    client: ~
    extensions:
        doctrine_ping_connection_extension: true
        doctrine_clear_identity_map_extension: true
        signal_extension: true
```

And in my client code I am using the producer as follows:

```
        $producer = $this->get('enqueue.producer');
        $producer->sendEvent($this->getParameter('queue_name'), '{"test": "body"}');
```

However, when I try to send the message I get the following response:

```
{"code":500,"message":"Error executing \"GetQueueUrl\" on \"https:\/\/sqs.eu-west-1.amazonaws.com\"; AWS HTTP error: Client error: `POST https:\/\/sqs.eu-west-1.amazonaws.com` resulted in a `400 Bad Request` response:\n<?xml version=\"1.0\"?><ErrorResponse xmlns=\"http:\/\/queue.amazonaws.com\/doc\/2012-11-05\/\"><Error><Type>Sender<\/Type><Code>A (truncated...)\n AWS.SimpleQueueService.NonExistentQueue (client): The specified queue does not exist for this wsdl version. - <?xml version=\"1.0\"?><ErrorResponse xmlns=\"http:\/\/queue.amazonaws.com\/doc\/2012-11-05\/\"><Error><Type>Sender<\/Type><Code>AWS.SimpleQueueService.NonExistentQueue<\/Code><Message>The specified queue does not exist for this wsdl version.<\/Message><Detail\/><\/Error><RequestId>6e18ae94-2a88-59f3-a4d1-fc7425e6d220<\/RequestId><\/ErrorResponse>"}
```

Does anyone have any advice to offer?
