### ISSUE TITLE
Transport is not enabled: amqp:

### ISSUE THREAD

**Issue by jhfyang** [php-enqueue/enqueue-dev#356]
Hello, I have installed enqueue as told in the documentation, however I get this error.

(1/1) LogicException
Transport is not enabled: amqp:
--
 Here is my config file:

```
enqueue:
    transport:
        default: "amqp:"
    client: ~
```

**Comment by makasim** [comment]
This is a correct behavior and it is supposed to work. I think the bug is in that line https://l.facebook.com/l.php?u=https%3A%2F%2Fgithub.com%2Fphp-enqueue%2Fenqueue-dev%2Fblob%2Fmaster%2Fpkg%2Fenqueue%2FSymfony%2FDefaultTransportFactory.php%23L61&h=ATPJU8kwfvC2hH5n1eTu1Wj4O2wzArZ2y87ZMGearFBcHGb5c-YCCriq1ak-MZ41Rqa8jGq6kZRS8hq9EZ4HKmSmb9_321HrcJYsOIRv1TUjYy4UKf9OKRdaaGAk9-w2AZvjg02MYDJdmh5E9rHC4A

I am going to fix it when I have time.

**Comment by jhfyang** [comment]
Thank you makasim for your reply!! Like you proposed me in PM 

This was the solution:

```
enqueue:
    transport:
        default: amqp
        amqp: "amqp:"
    client: ~
    async_events: true
```
