### ISSUE TITLE
Delayed-message doesn't work on my project !

### ISSUE THREAD

**Issue by A-contresens** [php-enqueue/enqueue-dev#373]
I didn't manage to make work delayed-message with amqp_lib

I have the error "Call to a member function send() on null"

My script :

```php
<?php

            $context = $this->container->get('enqueue.transport.context');
            $queue = $context->createQueue('fos_elastica_doctrine_orm_sync_index_with_object_change');

            $message = $context->createMessage(JSON::encode([
                'action' => $action,
                'model_class' =>"Planificateur\ItineraryBundle\Entity\ItineraryReferences",
                'model_id' => "stepId",
                'id' => $id,
                'index_name' => "itineraries",
                'type_name' => "itineraryReferences",
            ]));

            $context->createProducer()
                ->setDelayStrategy(new RabbitMqDlxDelayStrategy())
                ->setDeliveryDelay(5000)
                ->send($queue, $message);
```

Do you have an idea on what I'm making wrong?

If I delete : 

```php
<?php
 ->setDelayStrategy(new RabbitMqDlxDelayStrategy())
    ->setDeliveryDelay(5000)
```

It's working fine but without delay!

I have 
Symfony 3.4.4
php 7.1.4
rabbitMq 3.6.9 with the rabbitmq-delayed-message-exchange installed

My config.yml :

```yaml
enqueue:
    transport:
        default: 'amqp://user:password@rabbitmq_server:5672/'
    client: ~
```

Thanks

**Comment by makasim** [comment]
AMQP protocol does not define delaying so it is up to a broker.  To make it work you have to use rabbitmq_amqp transport:

```yaml
enqueue:
    transport:
        default: 'rabbitmq_amqp'
       rabbitmq_amqp: 'amqp://user:password@rabbitmq_server:5672/'
    client: ~
```

by default, it registers `dlx` strategy which does not require RabbitMQ's delay plugin to use the strategy based on delay plugin add an option:

```yaml
enqueue:
    transport:
        default: 'rabbitmq_amqp'
       rabbitmq_amqp:  
         dsn: 'amqp://user:password@rabbitmq_server:5672/'
         delay_strategy: delayed_message_plugin
    client: ~
```
