### ISSUE TITLE
[Symfony] Prepend enqueue_job_queue mapping for doctrine

### ISSUE THREAD

**Issue by ixarlie** [php-enqueue/enqueue-dev#431]
Hi,

I'm facing with an issue when trying to configure the enqueue_job_queue mapping in another doctrine entity manager connection.

I'm following the instructions:
```yaml
# doctrine.yml
  orm:
    default_entity_manager: default
      default:
        # default configuration with no EnqueueJobQueue mapping.
      enqueue:
        connection: enqueue
        mappings:
          EnqueueJobQueue:
            is_bundle: false
            type: xml
            dir: '%kernel.project_dir%/vendor/enqueue/job-queue/Doctrine/mapping'
            prefix: 'Enqueue\JobQueue\Doctrine\Entity'
```

But the prepend configuration done [in this extension method](https://github.com/php-enqueue/enqueue-dev/blob/9adbf015d3be1994ff172939de75cec872d4d866/pkg/enqueue-bundle/DependencyInjection/EnqueueExtension.php#L190), the JobStorage is not able to get the EntityManager for the `enqueue` connection.

How could I disable the prepend?

Thanks!
