### ISSUE TITLE
Exchange messages between applications

### ISSUE THREAD

**Issue by hpatoio** [php-enqueue/enqueue-dev#448]
I've 2 symfony applications and I need to consume in `ApplicationB` messages generated by `ApplicationA`

In `ApplicationA` I've

```
$message = new Message([
   'producer' => 'application_a',
   'produced_at' => (new \DateTime())->format('c'),
]);

$myProducer->sendEvent('from_a_to_b', $message);
```

In `ApplicationB` I've

```
class IncomingEmailProcessor implements PsrProcessor, TopicSubscriberInterface
{

    public static function getSubscribedTopics()
    {
        return [
            self::class => [
                'queueName' => 'from_a_to_b',
                'queueNameHardcoded' => true
            ]
        ];
    }

    public function process(PsrMessage $message, PsrContext $session)
    {
      // Do something
    }
}
```

But I don't receive any message on `ApplicationB` where do I go wrong ? 

This seems related to #296 and #196

**Comment by hpatoio** [comment]
In `ApplicationA` I've this command that I call using `foo` as queue name

```
class SendTestMessageCommand extends ContainerAwareCommand
{
    protected function configure()
    {
        $this
            ->setName('enqueue:send-test-message')
            ->setDescription('Send a test message')
            ->addOption('queue', null, InputOption::VALUE_REQUIRED, 'Queue's name');
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        if (!$input->getOption('queue')) {
            throw new \InvalidArgumentException("Please specify the 'queue'");
        }

        $queueName = $input->getOption('queue');

        $message = new Message([
            'producer' => 'test-command-applicationA',
            'body' => 'Hello from application A,
            'produced_at' => (new \DateTime())->format('c'),
        ]);

        $this->getContainer()->get('enqueue.producer')->sendEvent($queueName, $message);

    }
}
```

and this conf

```
enqueue:
    transport:
        default:
            alias: 'sqs'
        sqs:
            key: '%env(SQS_KEY)%'
            secret: '%env(SQS_SECRET)%'
            region: '%env(SQS_REGION)%'
    client:
        prefix: 'dev'
        app_name: applicationa
```

And in `ApplicationB 

```
enqueue:
    transport:
        default:
            alias: 'sqs'
        sqs:
            key: '%env(SQS_KEY)%'
            secret: '%env(SQS_SECRET)%'
            region: '%env(SQS_REGION)%'
    client:
        prefix: 'dev'
        app_name: applicationa
```
and the consumer

```
    musement.consumer.foo_consumer:
      class: 'App\Consumer\FooConsumer'
      public: true
      tags:
        - { name: 'enqueue.client.processor', queueName: 'foo', processorName: 'foo', topicName: 'foo' }
```

```
    public function process(PsrMessage $message, PsrContext $context)
    {
         $message = JSON::decode($message->getBody());
         var_dump($message);
         return self::ACK;
    }
```

I'm using `SQS` and I've a queue named `dev_dot_applicationa_dot_foo` configured. What I don't understand is: can I specify the *exact name* of the queue I wanna send the command to and the exact name of the queue for the consumer ? 

In application B, as you can see, I had to specifiy `applicationa` as application name because Enqueue build the name of the queue using the application name. But what if in my application B I want a consumer that also read messages for a queue configured for `applicationC` ?
