### ISSUE TITLE
[Symfony] sendCommand / sendEvent for delayed message have different behaviour

### ISSUE THREAD

**Issue by amenophis** [php-enqueue/enqueue-dev#523]
Hi,
we are trying to use `RabbitMqDlxDelayStrategy` with the `rabbitmq_amqp` transport in a symfony project. Our config looks like that:
```
enqueue:
    transport:
        default:
            alias: rabbitmq_amqp
        rabbitmq_amqp:
            driver: bunny
            host: '%env(RABBITMQ_HOST)%'
            user: '%env(RABBITMQ_USER)%'
            pass: '%env(RABBITMQ_PASSWORD)%'
            delay_strategy: dlx
    client:
        prefix: company
        app_name: webhook
        router_queue: router # Used id queue name (${prefix}.{app_name}.{router_queue})
        router_topic: router # Used id exchange name (${prefix}.{router_topic})
```
With `sendEvent`,  the delayed message is pushed in  `enqueue.company.webhook.job_execute.120000.delayed` for 120s, and then delivered to the  `company.webhook.job_execute` queue.

With `sendCommand`, the delayed message is pushed in  `enqueue.company.webhook.router.120000.delayed` for 120s. After the 120s it is sent to `enqueue.company.webhook.job_execute.120000.delayed` for 120s, and then delivered to the `company.webhook.job_execute` queue.

In both cases, we use the autowired `ProducerInterface` to `sendEvent`/`sendCommand`.

We are waiting for the same behaviour with Event or Command (The actual Event behaviour)

Is it a normal behaviour ? Is it a bug ?
Thanks
