### ISSUE TITLE
Command not processed on first registration

### ISSUE THREAD

**Issue by kabudu** [php-enqueue/enqueue-dev#529]
I appear to be having a problem where background-ed commands are not being processed using ```Symfony v4.1.4```, and often have to be registered two or three times before they get processed.

I am using ```redis``` as the transport mechanism.

My configuration in ```config/packages/enqueue.yaml``` is:

```
enqueue:
    transport:
        default: '%env(ENQUEUE_DSN)%'
        redis:
          dsn: '%env(ENQUEUE_DSN)%'
          vendor: 'predis'
    client: ~
```

I register commands using the following method:

```
       $this->messageProducer->sendCommand(
            '\Command\Processor\NamespacePath',
            ['job_id' => 1, 'entity_id' => 234]
        );
```

where ```$this->messageProducer``` is a DI provided dependency which is the default implementation of: ```Enqueue\Client\ProducerInterface```

I consume the commands using ```supervisord``` with the following configuration:

```
[program:enqueue_processor]
command=/var/www/html/bin/console --env=dev --time-limit="now + 5 minutes" enqueue:consume
process_name=%(program_name)s_%(process_num)02d
numprocs=1
autostart=true
autorestart=true
startsecs=0
user=apache
redirect_stderr=true
user=root
stdout_events_enabled=true
stderr_events_enabled=true
```

Any ideas?

**Comment by makasim** [comment]
How did you registered the command processor?

**Comment by kabudu** [comment]
> How did you register the command processor?

As a Symfony service, here is my definition below:

```
\Command\Processor\NamespacePath:
    public: true
    arguments:
      $logger: '@logger'
    tags:
      - { name: 'enqueue.client.processor', topicName: '\Command\Processor\NamespacePath' }
```

**Comment by makasim** [comment]
You registered a topic, not a command

It should be:

```
\Command\Processor\NamespacePath:
    public: true
    arguments:
      $logger: '@logger'
    tags:
      - { name: 'enqueue.client.processor', topicName: '__command__', processorName: '\Command\Processor\NamespacePath' }


```
