### ISSUE TITLE
Configuration with Amazon SQS and Symfony

### ISSUE THREAD

**Issue by noniagriconomie** [php-enqueue/enqueue-dev#619]
Hi

I plan to migrate from swarrot lib over rabbitmq to enqueue over amazon sqs.

I have found some documentation on the symfony bundle (I use version 3.4 lts) and the sqs library, and trying to configure it properly, but i face some problems:

```yml
enqueue:
    transport:
        default: 'sqs'
        sqs:
            key: '%app.amazonsqs.key%'
            secret: '%app.amazonsqs.secret%'
            token: ~
            region: 'eu-west-1'
            retries: 3
            version: '2012-11-05'
            lazy: true
    client: ~
```

```php
$producer->sendEvent(
            'QUEUE_URL.fifo',
            \json_encode(['id' => 42, 'a' => 'b'])
        );
```

And i got `The specified queue does not exist for this wsdl version`

What do i miss?

Many thanks for your time
