### ISSUE TITLE
Can I have multiple SQS connections?

### ISSUE THREAD

**Issue by gabyquiles** [php-enqueue/enqueue-dev#706]
Hi,
I want to receive messages from 2 SQS queues that are on 2 different sqs account.  Can I do that or does it support a single connection?
Thanks for your help

**Comment by makasim** [comment]
yes, you can create multiple sqs connections.

**Comment by gabyquiles** [comment]
Thanks for your fast response, could you direct me where to look?
should I add it as a transport, or the client key if the sqs configuration supports more than one config?

**Comment by makasim** [comment]
Could you tell more about your setup? Do you use a framework?

**Comment by gabyquiles** [comment]
I'm using symfony and already have enqueue, enqueue-bundle and sqs. If I setup a single connection it works perfectly, but I'm having problems adding the second set of credentials.

I saw that in the SqsConnectionFactory it is verifying if the configuration being passed is an array, and also found a previous issue with a pull request to pass an already configured sqs client. I tried to follow a similar approach. I defined my Sqs clients as services and tried to pass it as 
```
enqueue:
  transport:
     sqs:
       client: 
         - client1
         - client2
```
But I am getting
  Invalid type for path "enqueue.transport.sqs.client". Expected scalar, but got array.

**Comment by makasim** [comment]
You have to upgrade enqueue to 0.9 version and you will be able to configure multiple transports:

```
enqueue:
  foo: 
    transport: 'sqs:?key=foo&secret=bar'
  bar: 
    transport: 'sqs:?key=baz&secret=ololo'
```
