### ISSUE TITLE
Non-existent parameter "enqueue.default_client"

### ISSUE THREAD

**Issue by kabudu** [php-enqueue/enqueue-dev#707]
After upgrading to:

enqueue/enqueue-bundle: `0.9.3`
enqueue/redis: `0.9.2`

I haven't been able to get the configuration working for the enqueue bundle. 

This was the old configuration I had for the `0.8.*` version:

```
enqueue:
    transport:
        default: '%env(ENQUEUE_DSN)%'
        redis:
          dsn: '%env(ENQUEUE_DSN)%'
          vendor: 'predis'
    client: ~
```

Based on the documentation [here](https://github.com/php-enqueue/enqueue-dev/blob/master/docs/bundle/config_reference.md), I should be able to do the following:

```
enqueue:
  transport:
    dsn: '%env(ENQUEUE_DSN)%'
```

However, when I do that, I get the following error:

```
Unrecognized option "dsn" under "enqueue.transport". Available options are "async_commands", "async_events", "client", "consumption", "extensions", "job", "monitoring", "transport".
```

I then tried the following based on the feedback error messages:

```
enqueue:
  transport:
    transport: '%env(ENQUEUE_DSN)%'
```

and that resulted in the following error:

```
You have requested a non-existent parameter "enqueue.default_client".
```

which I traced the first occurrence to line 22, in the file: `vendor/enqueue/enqueue-bundle/Resources/config/services.yml`

Any ideas on:

a) How I can translate the old configuration into a format compatible with version `0.9.*`
b) How I can get the configuration working if there is no direct translation from the old configuration
c) What the issue might be?

Thanks...
