### ISSUE TITLE
Is the symfony bundle usable without enqueue/messenger-adapter?

### ISSUE THREAD

**Issue by leberknecht** [php-enqueue/enqueue-dev#721]
Hi, 

Im struggeling with plugging the symfony messenger to my google-pubsub bus via enqueue bundle. My config so far:
messenger.yml:
```
framework:
    messenger:
        transports:
            # Uncomment the following line to enable a transport named "amqp"
            # amqp: '%env(MESSENGER_TRANSPORT_DSN)%'
            enqueue: 'enqueue://gps'
        default_bus: messenger.bus.processBatch
        buses:
            messenger.bus.processBatch: ~
        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': amqp
            # Route your messages to the transports
            'App\Message\ProcessBatchMessage': enqueue
```
enqueue.yml:
```
enqueue:
    default:
        transport: 'gps'
        client: 
            driver_options:
                keyFilePath: "%env(GOOGLE_APPLICATION_CREDENTIALS)%"
                projectId: 'elucidate-co'

```
Im getting 

    No transport supports the given DSN "enqueue://gps"

I also tried with some other values. Debugging the TransportFactory showed that on `public function __construct(iterable $factories)` the factories only have one entry (for ampq). I read here https://github.com/php-enqueue/messenger-adapter/issues/5 that this might either be because of my outdated version or because some other bundle is missing (i think `enqueue/messenger-adapter`?)

Versions:
symfony/framework-bundle: 4.1.4
enqueue/enqueue: 0.9.6
enqueue/enqueue-bundle: 0.9.3
enqueue/gps: 0.9.3
symfony/messenger: 4.1.9

**Comment by leberknecht** [comment]
Ah sorry, forgot to mention: messenger-adapter requires framework 4.2., thats why im asking here instead simply trying if it solves the problem. Upgrading the framework would be expensive in my case.

**Comment by makasim** [comment]
@leberknecht you should use `enqueue://default` instead of `enqueue://gps`

**Comment by makasim** [comment]
and yes the bundle is a standalone, feature-rich solution.

**Comment by leberknecht** [comment]
Hm, didnt solved my problem :/ Same error. I see that the transport interface is pointing to 

    messenger.transport.enqueue                                                                      Symfony\Component\Messenger\Transport\TransportInterface 

i expected this to point to `GpsConnectionFactory`. I added this to the enqueue config
```
enqueue:
    default:
        transport: 
            dsn: 'gps:'
            connection_factory_class: Enqueue\Gps\GpsConnectionFactory
        client: 
            driver_options:
                keyFilePath: "%env(GOOGLE_APPLICATION_CREDENTIALS)%"
                projectId: 'elucidate-co'
```
but the container debug still shows sf TransportInterface oO Is there any documentation about how to use gps transport with the sf bundle?
