### ISSUE TITLE
[SQS][symfony bundle] Enable long polling to reduce the number of empty receives with 

### ISSUE THREAD

**Issue by CHenzel** [php-enqueue/enqueue-dev#778]
Hi,

Same as the issue https://github.com/php-enqueue/enqueue-dev/issues/307

I use the enqueue bundle for symfony with SQS, and the numberOfEmptyReceives in aws SQS  explode (> 5000), without send and consume any messages.

I try the setting "--receive-time=20000" but not working with consume command

`bin/console enqueue:consume --env=dev --receive-time=20000 => The "--receive-time" option does not exist.`

I think this setting change for --receive-timeout ?

`bin/console enqueue:consume --env=dev --receive-timeout=20000`

It's run but is not better and the value queue parameter **Receive Message Wait Time** still to 0.

How we can set **ReceiveMessageWaitTimeSeconds** to 20 seconds ? and **WaitTimeSeconds** in SqsConsumer to 20 seconds ? 

This is my `config.yml`

```
enqueue:
    default:
        transport: "sqs:?key=%amazon_web_services.key%&secret=%amazon_web_services.secret%&region=ca-central-1&lazy=true&retries=1"
        consumption:
            receive_timeout: 20000
        client:
            prefix: %kernel.environment%
            app_name: myapp
            traceable_producer: true
```
code for sent message

```
  /** @var ProducerInterface $producer **/
$producer = $this->container->get(\Enqueue\Client\ProducerInterface::class);
$producer->sendEvent('synchro_product_delete', serialize(['product_id' => $oldProductId]));
```
My service:

```
    product_delete_event_subscriber:
        class:ApiPublicBundle\EventListener\ProductDeleteEventSubscriber
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: 'enqueue.topic_subscriber', topicName: 'synchro_product_delete' }
```
My subscriber:

```
    public static function getSubscribedTopics()
    {
        return [
            [
                'topic' => 'synchro_product_delete',
                'queue' => 'enqueue_synchro_product_delete',
            ]
        ];
    }

    public function process(Message $message, Context $context)
    {
        $body = unserialize($message->getBody());
         //code
        return self::ACK;
    }
```
Thanks for your help

**Comment by CHenzel** [comment]
Edit :
For test, if i force WaitTimeSeconds to 20s in php class SqsConsumer, it's works no numberOfEmptyReceives anymore.

So How we can set **ReceiveMessageWaitTimeSeconds** to 20 seconds ? and **WaitTimeSeconds** in SqsConsumer to 20 seconds ?

**Comment by CHenzel** [comment]
Edit:

Apparently the problem comes from the consume function in the FallbackSubscriptionConsumer class

$message = 1 === $subscriberCount ? $consumer->receive($timeoutMs) : $consumer->receiveNoWait();

But i have several subscribers so receiveNoWait is use and bypass the configure timeOut, it's normal?

For the moment my only solution is to use a command by subscriber

bin/console enqueue:consume --env=dev enqueue_synchro_product_update
bin/console enqueue:consume --env=dev enqueue_synchro_product_delete
...

**Comment by makasim** [comment]
Amazon SQS does not support a consumption from multiple queues, hence FallbackSubscriptionConsumer does a kind of workaround. And, there is nothing we can do at our end to properly address the issue. 

You should run a consumer per queue so it uses `receive` method internally and there does not produce many requests to Amazon API.

**Comment by CHenzel** [comment]
Hello,

It's better than before. NumberOfEmptyReceives goes from 8000 to 30, but still not zero ...

490,297 queries empty since the beginning of the month by sending almost no messages from symfony.

I tried with the receive_timeout at 0 and 20000, and in both cases the WaitTimeSeconds is at 20 seconds in the SqsConsumer.php, so it's correct for me.

In aws sqs queue parameters : Receive Message Wait Time and Delivery Delay are set to 20

Does anyone have the same problem as me?

my config

```
enqueue:
    default:
        transport: "sqs:?key=%amazon_web_services.key%&secret=%amazon_web_services.secret%&region=ca-central-1&lazy=true&retries=1"
        consumption:
            receive_timeout: 20000
        client:
            prefix: %kernel.environment%
            app_name: my_app
            default_queue: 'default'
            traceable_producer: true
```

My supervisor

```
[program:pf_enqueue_synchro_object_update]
command=/var/www/bin/console enqueue:consume --env=staging --no-debug --time-limit="now + 60 minutes" --message-limit=50 enqueue_synchro_object_update
process_name=%(program_name)s_%(process_num)02d
numprocs=1
autostart=true
autorestart=true
startsecs=0
user=apache
redirect_stderr=true
stopsignal=KILL

[program:pf_enqueue_synchro_object_create]
command=/var/www/bin/console enqueue:consume --env=staging --no-debug --time-limit="now + 60 minutes" --message-limit=50 enqueue_synchro_object_create
process_name=%(program_name)s_%(process_num)02d
numprocs=1
autostart=true
autorestart=true
startsecs=0
user=apache
redirect_stderr=true
stopsignal=KILL
```
