### ISSUE TITLE
Enqueue DBAL DSN invalid

### ISSUE THREAD

**Issue by jean-gui** [php-enqueue/enqueue-dev#780]
Hi,

I am trying to setup the DBAL transport with SQLite in Symfony.
My enqueue.yml is:
```
enqueue:
    default:
        transport: '%env(resolve:DATABASE_URL)%'
        client: ~
```
An in my .env I have:
```
DATABASE_URL=sqlite:///%kernel.project_dir%/var/data.db
```

If I try to start Symfony console I get `Failed to parse DSN "sqlite:////*******/var/data.db"`

So I tried to tweak the DSN, but the only way to make it work is by putting a single /, but then if I try the command enqueue:setup-broker, I get `Failed to parse DSN "sqlite:////media/perso/PhpstormProjects/downloader/var/data.db"`

Am I doing something wrong?
