### ISSUE TITLE
[SQS][Question] Update from 0.8

### ISSUE THREAD

**Issue by KDederichs** [php-enqueue/enqueue-dev#784]
Hey,

I've been using version 0.8.x of enqueue with SQS for a while now and saw that there is a version 0.9.x available.
The problem is after switching my command Processors to the new interfaces and changing the config around it doesn't seem to send commands anymore.
The profiler says it sent the event but it doesn't appear in the SQS console and the consumer also receives nothing.

My ```enqueue.yaml``` config is:
```
enqueue:
  default:
    transport:
      dsn: "sqs::?key=%env(AWS_KEY)%&secret=%env(AWS_SECRET)%&region=%env(AWS_REGION)%"
      alias: 'sqs'
      sqs:
        key:                  "%env(AWS_KEY)%"
        secret:               "%env(AWS_SECRET)%"
        region:               "%env(AWS_REGION)%"
        retries:              3
        # the connection will be performed as later as possible, if the option set to true
        lazy:                 false
    client:
      traceable_producer:   true
      prefix:               enqueue
      app_name:             APP_NAME
      router_queue:         '%env(QUEUE_NAME)%-router'
      redelivered_delay_time: 0
```
And my ```enqueue_job_queue.yaml``` config is:
```
enqueue:
    default:
        job: true

doctrine:
    orm:
        mappings:
            EnqueueJobQueue:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/vendor/enqueue/job-queue/Doctrine/mapping'
                prefix: 'Enqueue\JobQueue\Doctrine\Entity'
```
(Also seems like I need a DSN now, while the sqs node was enough previously)

I'm sending the command normally over an injected ProducerInterface.

Does anyone have an idea where my messages might be stuck (or maybe if the config is wrong?)
