### ISSUE TITLE
How to set channel from multiply connections in config

### ISSUE THREAD

**Issue by demotivationme** [php-enqueue/enqueue-dev#828]
Is there a doc showing how to setup connection for message producers. For consumers it is 
"--client=" option.
Let me clarify what I meant. For example we have config:
```
enqueue:
    conn1:
        transport:
            dsn: 'amqp:'
    conn2:
        transport:
            dsn: 'amqp:'  
```
 And i want to send message exactly to conn2, how can I do this using ProducerInterface from docs

```

/** @var ProducerInterface $producer **/
$producer = $container->get(ProducerInterface::class);


// send event to many consumers
$producer->sendEvent('aFooTopic', 'Something has happened');

```
