### ISSUE TITLE
Message processor without default client

### ISSUE THREAD

**Issue by koderoff** [php-enqueue/enqueue-dev#835]
I setup enqueue for two clients something like this:

/config/packages/enqueue.yaml

```
enqueue:
    amqp:
        transport: '%env(resolve:ENQUEUE_DSN_AMQP)%'
        client: ~            
    kafka:
        transport: '%env(resolve:ENQUEUE_DSN_KAFKA)%'
        client: ~
```

/config/services.yaml

```
App\Async\ClickMessageProcessor:
    tags:
        - { name: 'enqueue.command_subscriber', client: 'kafka' }
```
Now I have two message processors which implements CommandSubscriberInterface and I want to bind each of them to his specific client. But the problem is that each processor that implements CommandSubscriberInterface is automatically registered with amqp client (which is default in my case). So, as a result I have ClickMessageProcessor that is registered with amqp client as well as kafka.

Is there a way to deal with this?

I am aware of **enqueue.processor** tag but it is not suits me because of losing flexibility of setting up the command
