### ISSUE TITLE
[fs] Dsn::parse() does not support Windows paths

### ISSUE THREAD

**Issue by Polylogic** [php-enqueue/enqueue-dev#851]
Hi. I'm trying to setup the enqueue/fs 0.9.8 transport in Symfony 4.2 on Windows platform, PHP 7.2.
My enqueue.yml is:
```
enqueue:
    default:
        transport: '%env(resolve:ENQUEUE_DSN)%'
        client: ~
```
.env file:
```
###> enqueue/enqueue-bundle ###
ENQUEUE_DSN=file://%kernel.project_dir%/var/queue
###< enqueue/enqueue-bundle ###
```
Unfortunately `parse_url($dsn, PHP_URL_PATH)` fails to parse strings like `file://C:\\path\\to/var/queue`. This way we get `['host' => 'C', 'path' => null]` which is obviously wrong.
