### ISSUE TITLE
[amqp-bunny] High CPU usage since 0.9.10

### ISSUE THREAD

**Issue by DamienHarper** [php-enqueue/enqueue-dev#854]
Since I updated to `amqp-bunny` from 0.9.9 to [0.9.10](https://github.com/php-enqueue/amqp-bunny/commit/1919ffec9a14012c0b0a98b8c9efb7592504a227), I am experiencing constant very high CPU usage.

I tracked down the root cause: I haven't set any `heartbeat` option in `enqueue.yml` file and since version 0.9.10, it is assumed as `heartbeat: 0` which causes the consumer to send heartbeat continuously (every 0s) to RabbitMQ rising up CPU usage to over 100% on each core.

Here is an excerpt of an `enqueue.yml` file causing constant high CPU usage:
```yaml
enqueue:
    default:
        transport: '%env(ENQUEUE_DSN)%'
        client:
            prefix: ''
            app_name: 'My app'
```

Here is an excerpt of my `enqueue.yml` file solving the issue:
```yaml
enqueue:
    default:
        transport: '%env(ENQUEUE_DSN)%'
        client:
            prefix: ''
            app_name: 'My app'
            driver_options:
                heartbeat: 60
```

Note: `enqueue.yml` format has changed since 0.9.8 but it is quite poorly documented or documentation has not been updated yet.
