### ISSUE TITLE
[SQS] config migration from 0.8 to 0.9

### ISSUE THREAD

**Issue by h0raz** [php-enqueue/enqueue-dev#915]
I'm currently upgrading a Symfony project from enqueue 0.8 to 0.9 using the sqs module

the old config was
```
enqueue:
    transport:
        default: sqs
        sqs:
            client: "aws.sqs"
    client:
        prefix: '%env(APP_ENVIRONMENT)%'
        app_name: '%env(APP_NAME)%'
``` 
current (broken) config
```
enqueue:
    default:
        transport:
            dsn: aws.sqs
        client:
            prefix: '%env(APP_ENVIRONMENT)%'
            app_name: '%env(APP_NAME)%'
```
in 0.9 the config changed and assumes a DSN, while the SqsConnectionFactory still allows a existing Aws/SqsClient

I get the error message `The DSN is invalid. It does not have scheme separator ":".` from `vendor/enqueue/enqueue/Doctrine/DoctrineConnectionFactoryFactory.php&line=43#line43`

In any example I found the config is being passed as array but not the aws.sqs as a service reference

I'd be happy if anyone could give me a hint on how to fix the config

**Comment by inverse** [comment]
Not an SQS user but what is `aws.sqs` shouldn't that represent a parameter/env-var? 

That should be in the format like `'sqs:?key=aKey&secret=aSecret&region=aRegion`

**Comment by h0raz** [comment]
`aws.sqs` is a reference
which was resolved in enqueue 0.8 to the aws.sqs client
and in 0.9 the config was unified and seems not possible anymore

the thing is that I don't want to configure this stuff multiple times
in aws I rely on the iam role of the container, so I actualy don't have a key, secret or region to put into
the aws sdk takes care of the credentials 

I solved it now with a custom factory servce

```
enqueue:
    default:
        transport:
          factory_service: "App\\Utils\\SqsCustomConnectionFactoryFactory"
          dsn: "sqs://"
```
 and the class
```
<?php

namespace App\Utils;

use Enqueue\ConnectionFactoryFactoryInterface;
use Enqueue\Sqs\SqsConnectionFactory;
use Interop\Queue\ConnectionFactory;
use Aws\Sqs\SqsClient;

class SqsCustomConnectionFactoryFactory implements ConnectionFactoryFactoryInterface
{

    /**
     * @var SqsClient
     */

    private $sqsClient;

    public function __construct(SqsClient $sqsClient)
    {
        $this->sqsClient = $sqsClient;
    }

    public function create($config): ConnectionFactory
    {
        return new SqsConnectionFactory($this->sqsClient);
    }
}

```
