### ISSUE TITLE
bin/console enqueue:setup-broker error on K8 

### ISSUE THREAD

**Issue by eheuje** [php-enqueue/enqueue-dev#993]
Hi,
Here's my config.

```yaml
enqueue:
    gps:
        transport:
            dsn: 'gps:'
        client:
            driver_options:
                keyFilePath: "%env(GOOGLE_JSON_CREDENTIAL)%"
                projectId: "%env(GOOGLE_CLOUD_PROJECT)%"
            prefix: foo
            app_name: api
            router_topic: topic
            router_queue: subscription
```
So, no particular stuff as you can seen.
When I call **bin/console enqueue:setup-broker**, this error is thrown.

```shell
In GrpcRequestWrapper.php line 257:

  [Google\Cloud\Core\Exception\ServiceException (7)]
  {
      "message": "Request had insufficient authentication scopes.",
      "code": 7,
      "status": "PERMISSION_DENIED",
      "details": [
          {
              "@type": "www-authenticate",
              "data": "Bearer realm=\"https:\/\/accounts.google.com\/\", error=\"insufficien
  t_scope\", scope=\"https:\/\/www.googleapis.com\/auth\/pubsub https:\/\/www.googleapis.com
  \/auth\/cloud-platform\""
          }
      ]
  }
```

My service account has the good rights and when I try to create topic with gcloud cli **with the same json credentials**, no problem at all. 

I'm on GKE.
